### ISSUE TITLE
IBM COS Sink Connector Timeout Exception with OpenShift/Strimzi

### ISSUE THREAD

**Issue by jackyng88** [ibm-messaging/kafka-connect-ibmcos-sink#9]
Hey, so I have an OpenShift cluster with a KafkaConnectS2I cluster using the Strimzi Operator. I've built the JAR/binaries and properly loaded it into the Kafka Connect cluster. However after providing a KafkaConnector yaml, the KafkaConnector custom resource just seems to not be able to connect to IBM COS.

```
Message:               PUT /connectors/cos-sink-connector/config returned 500 (Internal Server Error): IO Error trying to forward REST request: java.net.SocketTimeoutException: Connect Timeout
```

This is my .yaml file that I'm trying to use to configure the connector and have tried a few variations like changing the endpoint visibility to private/public and using various crn's but I just can't seem to connect?

```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: cos-sink-connector
  labels:
    strimzi.io/cluster: connect-cluster-101
spec:
  class: com.ibm.eventstreams.connect.cossink.COSSinkConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    topics: <topic>
    cos.api.key: <apiKey>
    cos.bucket.location: us-east
    cos.bucket.name: <cos-bucket-name>
    cos.bucket.resiliency: regional
    cos.service.crn: <crn::address>
    cos.endpoints.url: s3.us-east.cloud-object-storage.appdomain.cloud
    cos.object.records: 5
    cos.object.deadline.seconds: 5
    cos.object.interval.seconds: 5
    cos.endpoint.visibility: public
```
